# Generated by Django 3.1.4 on 2022-04-30 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_event_guest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='guest',
        ),
    ]
