# Generated by Django 3.1.4 on 2022-05-12 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0003_remove_event_guest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventattendees',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hotel.event'),
        ),
    ]
