# Generated by Django 3.1.4 on 2022-04-28 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0002_room_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='hotel',
            field=models.CharField(default='Dhara Hotels', max_length=20),
            preserve_default=False,
        ),
    ]
