# Generated by Django 3.1.4 on 2022-04-29 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0003_room_hotel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='payment_method',
            field=models.CharField(choices=[('VISA', 'VISA'), ('Cash', 'Cash'), ('Visa and Cash', 'Visa and Cash')], max_length=20),
        ),
    ]
