# Generated by Django 3.1.4 on 2022-04-29 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0004_auto_20220429_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='payment_method',
            field=models.CharField(max_length=20),
        ),
    ]
