# Generated by Django 3.1.4 on 2022-04-29 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0008_auto_20220429_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='hotel',
            field=models.CharField(default='HotelWithoutName', max_length=20),
            preserve_default=False,
        ),
    ]
