# Generated by Django 3.1.4 on 2022-05-12 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0009_auto_20220429_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='statusStartDate',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
